# Imports
from fastapi import APIRouter, Depends, HTTPException, Request, Form
from sqlalchemy.orm import Session
from typing import List, Optional
from database import SessionLocal, UserToken, PlaylistHistory, TrackHistory
from main import GetSessionData, RefreshAccessToken
from spotify_helpers import GetSpotifyHeaders

import requests

router = APIRouter()

# ------------------------
# Helper Functions
# ------------------------
def GetDatabase():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

# ------------------------
# Routes
# ------------------------

@router.post("/spotify/save-tracks")
def SaveTracks(request: Request, trackIDs: List[str], db: Session = Depends(GetDatabase)):
    session = GetSessionData(request)
    if not session:
        raise HTTPException(status_code=401, detail="Not logged in")

    userToken = db.query(UserToken).filter(UserToken.UserID == session["user_id"]).first()
    if not userToken:
        raise HTTPException(status_code=401, detail="Missing tokens")

    token = RefreshAccessToken(userToken, db)
    for i in range(0, len(trackIDs), 50):
        chunk = trackIDs[i:i + 50]
        r = requests.put(
            "https://api.spotify.com/v1/me/tracks",
            headers=GetSpotifyHeaders(token),
            json={"ids": chunk}
        )
        if r.status_code != 200:
            raise HTTPException(status_code=r.status_code, detail=r.text)
    return {"status": "ok", "saved": len(trackIDs)}

@router.post("/spotify/create-playlist")
def CreatePlaylist(
        request: Request,
        name: str = Form(...),
        description: str = Form(""),
        public: bool = Form(False),
        track_uris: Optional[List[str]] = Form(None),
        db: Session = Depends(GetDatabase),
):
    session = GetSessionData(request)
    if not session:
        raise HTTPException(status_code=401, detail="Not logged in")

    userToken = db.query(UserToken).filter(UserToken.UserID == session["user_id"]).first()
    token = RefreshAccessToken(userToken, db)

    me = requests.get("https://api.spotify.com/v1/me", headers=GetSpotifyHeaders(token)).json()
    payload = {"name": name, "description": description, "public": public}
    r = requests.post(
        f"https://api.spotify.com/v1/users/{me['id']}/playlists",
        headers=GetSpotifyHeaders(token),
        json=payload
    )

    if r.status_code not in (200, 201):
        raise HTTPException(status_code=r.status_code, detail=r.text)
    playlist = r.json()

    if track_uris:
        requests.post(
            f"https://api.spotify.com/v1/playlists/{playlist['id']}/tracks",
            headers=GetSpotifyHeaders(token),
            json={"uris": track_uris}
        )

    # Log playlist
    entry = PlaylistHistory(
        UserID=userToken.ID,
        Mood="custom",
        Source="manual",
        SpotifyPlaylistID=playlist["id"],
        SpotifyURL=playlist["external_urls"]["spotify"],
        AutoCreated=False,
        TrackCount=len(track_uris or []),
    )
    db.add(entry)
    db.commit()

    return {"playlist": playlist}

@router.post("/spotify/audio-features")
def AudioFeatures(request: Request, ids: str, db: Session = Depends(GetDatabase)):
    session = GetSessionData(request)
    if not session:
        raise HTTPException(status_code=401, detail="Not logged in")

    userToken = db.query(UserToken).filter(UserToken.UserID == session["user_id"]).first()
    token = RefreshAccessToken(userToken, db)
    r = requests.get(
        f"https://api.spotify.com/v1/audio-features?ids={ids}",
        headers=GetSpotifyHeaders(token),
    )
    if r.status_code != 200:
        raise HTTPException(status_code=r.status_code, detail=r.text)
    return r.json()

# ------------------------
# History Endpoints
# ------------------------

@router.get("/spotify/recent-playlists")
def RecentPlaylists(request: Request, db: Session = Depends(GetDatabase), limit: int = 10):
    """Return the user's most recent playlists generated by Moodify."""
    session = GetSessionData(request)
    if not session:
        raise HTTPException(status_code=401, detail="Not logged in")

    userToken = db.query(UserToken).filter(UserToken.UserID == session["user_id"]).first()
    history = (
        db.query(PlaylistHistory)
        .filter(PlaylistHistory.UserID == userToken.ID)
        .order_by(PlaylistHistory.CreatedAt.desc())
        .limit(limit)
        .all()
    )

    return [
        {
            "mood": h.Mood,
            "source": h.Source,
            "spotify_url": h.SpotifyURL,
            "created_at": h.CreatedAt.isoformat(),
            "track_count": h.TrackCount,
            "auto_created": bool(h.AutoCreated),
        }
        for h in history
    ]

@router.get("/spotify/recent-tracks")
def RecentTracks(request: Request, db: Session = Depends(GetDatabase), limit: int = 20, mood: str | None = None):
    """Return the user's most recently recommended tracks."""
    session = GetSessionData(request)
    if not session:
        raise HTTPException(status_code=401, detail="Not logged in")

    userToken = db.query(UserToken).filter(UserToken.UserID == session["user_id"]).first()

    query = db.query(TrackHistory).filter(TrackHistory.UserID == userToken.ID)
    if mood:
        query = query.filter(TrackHistory.Mood == mood)

    results = query.order_by(TrackHistory.Timestamp.desc()).limit(limit).all()

    return [
        {
            "track_name": t.TrackName,
            "artist_name": t.ArtistName,
            "mood": t.Mood,
            "source": t.Source,
            "spotify_url": t.SpotifyURL,
            "preview_url": t.PreviewURL,
            "timestamp": t.Timestamp.isoformat(),
        }
        for t in results
    ]

